// Code generated by protoc-gen-go. DO NOT EDIT.
// source: arith.proto

/*
Package Arith is a generated protocol buffer package.

It is generated from these files:
	arith.proto

It has these top-level messages:
	Args
	Reply
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Args struct {
	A                *int32 `protobuf:"varint,1,opt,name=A" json:"A,omitempty"`
	B                *int32 `protobuf:"varint,2,opt,name=B" json:"B,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Args) Reset()                    { *m = Args{} }
func (m *Args) String() string            { return proto.CompactTextString(m) }
func (*Args) ProtoMessage()               {}
func (*Args) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Args) GetA() int32 {
	if m != nil && m.A != nil {
		return *m.A
	}
	return 0
}

func (m *Args) GetB() int32 {
	if m != nil && m.B != nil {
		return *m.B
	}
	return 0
}

type Reply struct {
	C                *int32 `protobuf:"varint,1,opt,name=C" json:"C,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Reply) Reset()                    { *m = Reply{} }
func (m *Reply) String() string            { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()               {}
func (*Reply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Reply) GetC() int32 {
	if m != nil && m.C != nil {
		return *m.C
	}
	return 0
}

func init() {
	proto.RegisterType((*Args)(nil), "Arith.Args")
	proto.RegisterType((*Reply)(nil), "Arith.Reply")
}

func init() { proto.RegisterFile("arith.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 109 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x2c, 0xca, 0x2c,
	0xc9, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x75, 0x04, 0x71, 0x94, 0x94, 0xb8, 0x58,
	0x1c, 0x8b, 0xd2, 0x8b, 0x85, 0x78, 0xb8, 0x18, 0x1d, 0x25, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83,
	0x18, 0x1d, 0x41, 0x3c, 0x27, 0x09, 0x26, 0x08, 0xcf, 0x49, 0x49, 0x94, 0x8b, 0x35, 0x28, 0xb5,
	0x20, 0xa7, 0x12, 0x24, 0xec, 0x0c, 0x53, 0xe4, 0xec, 0x24, 0xc3, 0x25, 0x9c, 0x9c, 0x9f, 0xab,
	0x97, 0x94, 0x98, 0x99, 0x52, 0xaa, 0x57, 0x54, 0x90, 0xac, 0x07, 0x36, 0xd1, 0x09, 0x62, 0x30,
	0x20, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x86, 0xce, 0xf8, 0x6d, 0x00, 0x00, 0x00,
}
