// Code generated by protoc-gen-go. DO NOT EDIT.
// source: baidu/rpc/policy/baidu_rpc_meta.proto

/*
Package baidu_rpc is a generated protocol buffer package.

It is generated from these files:
	baidu/rpc/policy/baidu_rpc_meta.proto
	baidu/rpc/policy/hulu_pbrpc_meta.proto
	baidu/rpc/policy/mongo.proto
	baidu/rpc/policy/nshead_meta.proto
	baidu/rpc/policy/public_pbrpc_meta.proto
	baidu/rpc/policy/sofa_pbrpc_meta.proto
	baidu/rpc/policy/streaming_rpc_meta.proto

It has these top-level messages:
	RpcMeta
	RpcRequestMeta
	RpcResponseMeta
	HuluRpcRequestMeta
	HuluRpcResponseMeta
	MongoHeader
	MongoRequest
	MongoResponse
	NsheadMeta
	PublicPbrpcRequest
	RequestHead
	RequestBody
	PublicPbrpcResponse
	ResponseHead
	ResponseBody
	SofaRpcMeta
	StreamSettings
	StreamFrameMeta
	Feedback
*/
package baidu_rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import baidu_rpc1 "github.com/fast01/rpcx/codec/brpc/proto/baidu/rpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RpcMeta struct {
	Request            *RpcRequestMeta       `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
	Response           *RpcResponseMeta      `protobuf:"bytes,2,opt,name=response" json:"response,omitempty"`
	CompressType       *int32                `protobuf:"varint,3,opt,name=compress_type,json=compressType" json:"compress_type,omitempty"`
	CorrelationId      *int64                `protobuf:"varint,4,opt,name=correlation_id,json=correlationId" json:"correlation_id,omitempty"`
	AttachmentSize     *int32                `protobuf:"varint,5,opt,name=attachment_size,json=attachmentSize" json:"attachment_size,omitempty"`
	ChunkInfo          *baidu_rpc1.ChunkInfo `protobuf:"bytes,6,opt,name=chunk_info,json=chunkInfo" json:"chunk_info,omitempty"`
	AuthenticationData []byte                `protobuf:"bytes,7,opt,name=authentication_data,json=authenticationData" json:"authentication_data,omitempty"`
	StreamSettings     *StreamSettings       `protobuf:"bytes,8,opt,name=stream_settings,json=streamSettings" json:"stream_settings,omitempty"`
	XXX_unrecognized   []byte                `json:"-"`
}

func (m *RpcMeta) Reset()                    { *m = RpcMeta{} }
func (m *RpcMeta) String() string            { return proto.CompactTextString(m) }
func (*RpcMeta) ProtoMessage()               {}
func (*RpcMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RpcMeta) GetRequest() *RpcRequestMeta {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *RpcMeta) GetResponse() *RpcResponseMeta {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *RpcMeta) GetCompressType() int32 {
	if m != nil && m.CompressType != nil {
		return *m.CompressType
	}
	return 0
}

func (m *RpcMeta) GetCorrelationId() int64 {
	if m != nil && m.CorrelationId != nil {
		return *m.CorrelationId
	}
	return 0
}

func (m *RpcMeta) GetAttachmentSize() int32 {
	if m != nil && m.AttachmentSize != nil {
		return *m.AttachmentSize
	}
	return 0
}

func (m *RpcMeta) GetChunkInfo() *baidu_rpc1.ChunkInfo {
	if m != nil {
		return m.ChunkInfo
	}
	return nil
}

func (m *RpcMeta) GetAuthenticationData() []byte {
	if m != nil {
		return m.AuthenticationData
	}
	return nil
}

func (m *RpcMeta) GetStreamSettings() *StreamSettings {
	if m != nil {
		return m.StreamSettings
	}
	return nil
}

type RpcRequestMeta struct {
	ServiceName      *string `protobuf:"bytes,1,req,name=service_name,json=serviceName" json:"service_name,omitempty"`
	MethodName       *string `protobuf:"bytes,2,req,name=method_name,json=methodName" json:"method_name,omitempty"`
	LogId            *int64  `protobuf:"varint,3,opt,name=log_id,json=logId" json:"log_id,omitempty"`
	TraceId          *int64  `protobuf:"varint,4,opt,name=trace_id,json=traceId" json:"trace_id,omitempty"`
	SpanId           *int64  `protobuf:"varint,5,opt,name=span_id,json=spanId" json:"span_id,omitempty"`
	ParentSpanId     *int64  `protobuf:"varint,6,opt,name=parent_span_id,json=parentSpanId" json:"parent_span_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RpcRequestMeta) Reset()                    { *m = RpcRequestMeta{} }
func (m *RpcRequestMeta) String() string            { return proto.CompactTextString(m) }
func (*RpcRequestMeta) ProtoMessage()               {}
func (*RpcRequestMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RpcRequestMeta) GetServiceName() string {
	if m != nil && m.ServiceName != nil {
		return *m.ServiceName
	}
	return ""
}

func (m *RpcRequestMeta) GetMethodName() string {
	if m != nil && m.MethodName != nil {
		return *m.MethodName
	}
	return ""
}

func (m *RpcRequestMeta) GetLogId() int64 {
	if m != nil && m.LogId != nil {
		return *m.LogId
	}
	return 0
}

func (m *RpcRequestMeta) GetTraceId() int64 {
	if m != nil && m.TraceId != nil {
		return *m.TraceId
	}
	return 0
}

func (m *RpcRequestMeta) GetSpanId() int64 {
	if m != nil && m.SpanId != nil {
		return *m.SpanId
	}
	return 0
}

func (m *RpcRequestMeta) GetParentSpanId() int64 {
	if m != nil && m.ParentSpanId != nil {
		return *m.ParentSpanId
	}
	return 0
}

type RpcResponseMeta struct {
	ErrorCode        *int32  `protobuf:"varint,1,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	ErrorText        *string `protobuf:"bytes,2,opt,name=error_text,json=errorText" json:"error_text,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RpcResponseMeta) Reset()                    { *m = RpcResponseMeta{} }
func (m *RpcResponseMeta) String() string            { return proto.CompactTextString(m) }
func (*RpcResponseMeta) ProtoMessage()               {}
func (*RpcResponseMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RpcResponseMeta) GetErrorCode() int32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func (m *RpcResponseMeta) GetErrorText() string {
	if m != nil && m.ErrorText != nil {
		return *m.ErrorText
	}
	return ""
}

func init() {
	proto.RegisterType((*RpcMeta)(nil), "baidu.rpc.RpcMeta")
	proto.RegisterType((*RpcRequestMeta)(nil), "baidu.rpc.RpcRequestMeta")
	proto.RegisterType((*RpcResponseMeta)(nil), "baidu.rpc.RpcResponseMeta")
}

func init() { proto.RegisterFile("baidu/rpc/policy/baidu_rpc_meta.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 485 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x92, 0xdb, 0x6e, 0x13, 0x31,
	0x10, 0x86, 0xb5, 0x0d, 0x39, 0x4d, 0x4e, 0x92, 0x29, 0xea, 0x36, 0x12, 0x22, 0x04, 0x22, 0xc2,
	0x4d, 0x22, 0x51, 0x89, 0x07, 0x48, 0xb9, 0xc9, 0x05, 0x07, 0x39, 0xbd, 0x5f, 0x19, 0x7b, 0x9a,
	0x58, 0x64, 0x6d, 0x63, 0x4f, 0x50, 0xd3, 0xf7, 0xe0, 0x91, 0x78, 0x2f, 0xb4, 0xde, 0xa4, 0x39,
	0xf4, 0x6e, 0xe7, 0xff, 0xbf, 0x99, 0x1d, 0xff, 0x1a, 0x18, 0xfd, 0x14, 0x5a, 0x6d, 0xa6, 0xde,
	0xc9, 0xa9, 0xb3, 0x6b, 0x2d, 0xb7, 0xd3, 0x28, 0x64, 0xde, 0xc9, 0x2c, 0x47, 0x12, 0x13, 0xe7,
	0x2d, 0x59, 0xd6, 0x8c, 0xea, 0xc4, 0x3b, 0xd9, 0xbf, 0x3a, 0x74, 0x58, 0x47, 0xda, 0x9a, 0x50,
	0x32, 0xfd, 0x8f, 0xcf, 0x46, 0x05, 0xf2, 0x28, 0x72, 0x6d, 0x96, 0x67, 0xe3, 0x86, 0x7f, 0x2b,
	0x50, 0xe7, 0x4e, 0x7e, 0x45, 0x12, 0xec, 0x06, 0xea, 0x1e, 0x7f, 0x6f, 0x30, 0x50, 0x9a, 0x0c,
	0x92, 0x71, 0xeb, 0xd3, 0xf5, 0xe4, 0xe9, 0x67, 0x13, 0xee, 0x24, 0x2f, 0xcd, 0x82, 0xe5, 0x7b,
	0x92, 0x7d, 0x86, 0x86, 0xc7, 0xe0, 0xac, 0x09, 0x98, 0x5e, 0xc4, 0xae, 0xfe, 0x79, 0x57, 0xe9,
	0xc6, 0xb6, 0x27, 0x96, 0xbd, 0x83, 0x8e, 0xb4, 0xb9, 0xf3, 0x18, 0x42, 0x46, 0x5b, 0x87, 0x69,
	0x65, 0x90, 0x8c, 0xab, 0xbc, 0xbd, 0x17, 0xef, 0xb6, 0x0e, 0xd9, 0x08, 0xba, 0xd2, 0x7a, 0x8f,
	0x6b, 0x51, 0x3c, 0x2f, 0xd3, 0x2a, 0x7d, 0x31, 0x48, 0xc6, 0x15, 0xde, 0x39, 0x52, 0xe7, 0x8a,
	0x7d, 0x80, 0x9e, 0x20, 0x12, 0x72, 0x95, 0xa3, 0xa1, 0x2c, 0xe8, 0x47, 0x4c, 0xab, 0x71, 0x5a,
	0xf7, 0x20, 0x2f, 0xf4, 0x23, 0xb2, 0x1b, 0x00, 0xb9, 0xda, 0x98, 0x5f, 0x99, 0x36, 0xf7, 0x36,
	0xad, 0xc5, 0x75, 0x2f, 0x8f, 0xd6, 0xbd, 0x2d, 0xcc, 0xb9, 0xb9, 0xb7, 0xbc, 0x29, 0xf7, 0x9f,
	0x6c, 0x0a, 0x2f, 0xc5, 0x86, 0x56, 0x68, 0x48, 0xcb, 0x72, 0x0f, 0x25, 0x48, 0xa4, 0xf5, 0x41,
	0x32, 0x6e, 0x73, 0x76, 0x6a, 0x7d, 0x11, 0x24, 0xd8, 0x0c, 0x7a, 0x65, 0xde, 0x59, 0x40, 0x22,
	0x6d, 0x96, 0x21, 0x6d, 0x3c, 0xcb, 0x73, 0x11, 0x89, 0xc5, 0x0e, 0xe0, 0xdd, 0x70, 0x52, 0x0f,
	0xff, 0x25, 0xd0, 0x3d, 0x8d, 0x9c, 0xbd, 0x85, 0x76, 0x40, 0xff, 0x47, 0x4b, 0xcc, 0x8c, 0xc8,
	0x31, 0x4d, 0x06, 0x17, 0xe3, 0x26, 0x6f, 0xed, 0xb4, 0x6f, 0x22, 0x47, 0xf6, 0x06, 0x5a, 0x39,
	0xd2, 0xca, 0xaa, 0x92, 0xb8, 0x88, 0x04, 0x94, 0x52, 0x04, 0x5e, 0x41, 0x6d, 0x6d, 0x97, 0x45,
	0x90, 0x95, 0x18, 0x64, 0x75, 0x6d, 0x97, 0x73, 0xc5, 0xae, 0xa1, 0x41, 0x5e, 0x48, 0x3c, 0x24,
	0x5c, 0x8f, 0xf5, 0x5c, 0xb1, 0x2b, 0xa8, 0x07, 0x27, 0x62, 0xf6, 0xd5, 0xe8, 0xd4, 0x8a, 0x72,
	0xae, 0xd8, 0x7b, 0xe8, 0x3a, 0xe1, 0x63, 0xe0, 0x3b, 0xbf, 0x16, 0xfd, 0x76, 0xa9, 0x2e, 0x22,
	0x35, 0xfc, 0x0e, 0xbd, 0xb3, 0x1b, 0x60, 0xaf, 0x01, 0xd0, 0x7b, 0xeb, 0x33, 0x69, 0x15, 0xc6,
	0x4b, 0xab, 0xf2, 0x66, 0x54, 0x6e, 0xad, 0xc2, 0x83, 0x4d, 0xf8, 0x40, 0xf1, 0xa4, 0x9a, 0x3b,
	0xfb, 0x0e, 0x1f, 0x68, 0x36, 0x82, 0x4b, 0x69, 0xf3, 0xa3, 0x20, 0xcb, 0x0b, 0x9f, 0x75, 0x66,
	0x85, 0xc2, 0x9d, 0xfc, 0x51, 0xdc, 0xf5, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x36, 0xe7, 0xfd,
	0x34, 0x4e, 0x03, 0x00, 0x00,
}
