// Code generated by protoc-gen-go. DO NOT EDIT.
// source: uidmap.proto

/*
Package demo_uidmap is a generated protocol buffer package.

It is generated from these files:
	uidmap.proto

It has these top-level messages:
	AccountInfo
	QueryUidRequest
	QueryUidResponse
*/
package demo_uidmap

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ECode int32

const (
	ECode_SUCCESS           ECode = 0
	ECode_FAIL              ECode = -10001
	ECode_NOT_EXIST         ECode = -10002
	ECode_CLINENT_FORBIDDEN ECode = -10003
	ECode_CLIENT_ERROR      ECode = -10004
)

var ECode_name = map[int32]string{
	0:      "SUCCESS",
	-10001: "FAIL",
	-10002: "NOT_EXIST",
	-10003: "CLINENT_FORBIDDEN",
	-10004: "CLIENT_ERROR",
}
var ECode_value = map[string]int32{
	"SUCCESS":           0,
	"FAIL":              -10001,
	"NOT_EXIST":         -10002,
	"CLINENT_FORBIDDEN": -10003,
	"CLIENT_ERROR":      -10004,
}

func (x ECode) Enum() *ECode {
	p := new(ECode)
	*p = x
	return p
}
func (x ECode) String() string {
	return proto.EnumName(ECode_name, int32(x))
}
func (x *ECode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ECode_value, data, "ECode")
	if err != nil {
		return err
	}
	*x = ECode(value)
	return nil
}
func (ECode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AccountType int32

const (
	AccountType_UNKNOWN AccountType = 0
	AccountType_NORMAL  AccountType = 1
	AccountType_THIRD   AccountType = 2
)

var AccountType_name = map[int32]string{
	0: "UNKNOWN",
	1: "NORMAL",
	2: "THIRD",
}
var AccountType_value = map[string]int32{
	"UNKNOWN": 0,
	"NORMAL":  1,
	"THIRD":   2,
}

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}
func (x AccountType) String() string {
	return proto.EnumName(AccountType_name, int32(x))
}
func (x *AccountType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AccountType_value, data, "AccountType")
	if err != nil {
		return err
	}
	*x = AccountType(value)
	return nil
}
func (AccountType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type AccountFlag int32

const (
	AccountFlag_INIT    AccountFlag = 0
	AccountFlag_ACTIVE  AccountFlag = 1
	AccountFlag_DISABLE AccountFlag = 2
)

var AccountFlag_name = map[int32]string{
	0: "INIT",
	1: "ACTIVE",
	2: "DISABLE",
}
var AccountFlag_value = map[string]int32{
	"INIT":    0,
	"ACTIVE":  1,
	"DISABLE": 2,
}

func (x AccountFlag) Enum() *AccountFlag {
	p := new(AccountFlag)
	*p = x
	return p
}
func (x AccountFlag) String() string {
	return proto.EnumName(AccountFlag_name, int32(x))
}
func (x *AccountFlag) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AccountFlag_value, data, "AccountFlag")
	if err != nil {
		return err
	}
	*x = AccountFlag(value)
	return nil
}
func (AccountFlag) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type AccountInfo struct {
	Type             *AccountType `protobuf:"varint,1,req,name=type,enum=demo.uidmap.AccountType" json:"type,omitempty"`
	Id               *uint64      `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Flag             *int32       `protobuf:"varint,3,opt,name=flag" json:"flag,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *AccountInfo) Reset()                    { *m = AccountInfo{} }
func (m *AccountInfo) String() string            { return proto.CompactTextString(m) }
func (*AccountInfo) ProtoMessage()               {}
func (*AccountInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AccountInfo) GetType() AccountType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return AccountType_UNKNOWN
}

func (m *AccountInfo) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *AccountInfo) GetFlag() int32 {
	if m != nil && m.Flag != nil {
		return *m.Flag
	}
	return 0
}

type QueryUidRequest struct {
	Accinfo          *AccountInfo `protobuf:"bytes,1,req,name=accinfo" json:"accinfo,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *QueryUidRequest) Reset()                    { *m = QueryUidRequest{} }
func (m *QueryUidRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryUidRequest) ProtoMessage()               {}
func (*QueryUidRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *QueryUidRequest) GetAccinfo() *AccountInfo {
	if m != nil {
		return m.Accinfo
	}
	return nil
}

type QueryUidResponse struct {
	Status           *ECode       `protobuf:"varint,1,req,name=status,enum=demo.uidmap.ECode" json:"status,omitempty"`
	Msg              *string      `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Uid              *AccountInfo `protobuf:"bytes,3,opt,name=uid" json:"uid,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *QueryUidResponse) Reset()                    { *m = QueryUidResponse{} }
func (m *QueryUidResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryUidResponse) ProtoMessage()               {}
func (*QueryUidResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *QueryUidResponse) GetStatus() ECode {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ECode_SUCCESS
}

func (m *QueryUidResponse) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func (m *QueryUidResponse) GetUid() *AccountInfo {
	if m != nil {
		return m.Uid
	}
	return nil
}

func init() {
	proto.RegisterType((*AccountInfo)(nil), "demo.uidmap.AccountInfo")
	proto.RegisterType((*QueryUidRequest)(nil), "demo.uidmap.QueryUidRequest")
	proto.RegisterType((*QueryUidResponse)(nil), "demo.uidmap.QueryUidResponse")
	proto.RegisterEnum("demo.uidmap.ECode", ECode_name, ECode_value)
	proto.RegisterEnum("demo.uidmap.AccountType", AccountType_name, AccountType_value)
	proto.RegisterEnum("demo.uidmap.AccountFlag", AccountFlag_name, AccountFlag_value)
}

func init() { proto.RegisterFile("uidmap.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x91, 0xdf, 0x8e, 0xd2, 0x40,
	0x14, 0xc6, 0x77, 0x4a, 0x61, 0xe5, 0xb0, 0xae, 0xb3, 0xe7, 0xc2, 0x54, 0xa3, 0x86, 0x70, 0x45,
	0x1a, 0x43, 0x94, 0x37, 0x28, 0x65, 0xc8, 0x4e, 0xac, 0xd3, 0x38, 0x2d, 0xfe, 0xb9, 0x22, 0x4d,
	0x3b, 0x90, 0x26, 0x0b, 0xed, 0xd2, 0xd6, 0x04, 0xe3, 0x85, 0x97, 0xbe, 0x8e, 0xef, 0xe5, 0x9f,
	0x47, 0xd0, 0x4c, 0x8b, 0xe0, 0x1a, 0xdd, 0x5e, 0x9d, 0x9c, 0xef, 0xd7, 0xef, 0x7c, 0x73, 0x0e,
	0x9c, 0x55, 0x69, 0xb2, 0x8e, 0xf2, 0x51, 0xbe, 0xcd, 0xca, 0x0c, 0x7b, 0x89, 0x5a, 0x67, 0xa3,
	0xa6, 0x35, 0x58, 0x40, 0xcf, 0x89, 0xe3, 0xac, 0xda, 0x94, 0x7c, 0xb3, 0xcc, 0xf0, 0x29, 0x98,
	0xe5, 0x2e, 0x57, 0x16, 0xe9, 0x1b, 0xc3, 0xf3, 0xb1, 0x35, 0xfa, 0x03, 0x1d, 0xed, 0xb9, 0x70,
	0x97, 0x2b, 0x59, 0x53, 0x78, 0x0e, 0x46, 0x9a, 0x58, 0x46, 0xdf, 0x18, 0x9a, 0xd2, 0x48, 0x13,
	0x44, 0x30, 0x97, 0x57, 0xd1, 0xca, 0x6a, 0xf5, 0xc9, 0xb0, 0x2d, 0xeb, 0x7a, 0xc0, 0xe0, 0xde,
	0xab, 0x4a, 0x6d, 0x77, 0xf3, 0x34, 0x91, 0xea, 0xba, 0x52, 0x45, 0x89, 0x63, 0x38, 0x8d, 0xe2,
	0x38, 0xdd, 0x2c, 0xb3, 0x7a, 0x4e, 0xef, 0xdf, 0x73, 0x74, 0x1e, 0xf9, 0x1b, 0x1c, 0x7c, 0x04,
	0x7a, 0xb4, 0x29, 0xf2, 0x6c, 0x53, 0x28, 0xb4, 0xa1, 0x53, 0x94, 0x51, 0x59, 0x15, 0xfb, 0xb8,
	0x78, 0xc3, 0x86, 0xb9, 0x59, 0xa2, 0xe4, 0x9e, 0x40, 0x0a, 0xad, 0x75, 0xb1, 0xb2, 0x8c, 0x3e,
	0x19, 0x76, 0xa5, 0x2e, 0xd1, 0x86, 0x56, 0x95, 0x26, 0x75, 0xd6, 0xdb, 0x12, 0x68, 0xc8, 0xfe,
	0x00, 0xed, 0xda, 0x0e, 0x7b, 0x70, 0x1a, 0xcc, 0x5d, 0x97, 0x05, 0x01, 0x3d, 0xc1, 0x0b, 0x30,
	0x67, 0x0e, 0xf7, 0xe8, 0x8f, 0x2f, 0x3f, 0x9b, 0x8f, 0xe0, 0x7d, 0xe8, 0x0a, 0x3f, 0x5c, 0xb0,
	0xb7, 0x3c, 0x08, 0xe9, 0xf7, 0x63, 0xff, 0x09, 0x5c, 0xb8, 0x1e, 0x17, 0x4c, 0x84, 0x8b, 0x99,
	0x2f, 0x27, 0x7c, 0x3a, 0x65, 0x82, 0x7e, 0x3b, 0xea, 0x0f, 0xe0, 0xcc, 0xf5, 0xb8, 0x96, 0x99,
	0x94, 0xbe, 0xa4, 0x5f, 0x0f, 0x92, 0xfd, 0xfc, 0x70, 0x21, 0xbd, 0x79, 0x9d, 0x60, 0x2e, 0x5e,
	0x08, 0xff, 0x8d, 0xa0, 0x27, 0x08, 0xd0, 0x11, 0xbe, 0x7c, 0xe9, 0x78, 0x94, 0x60, 0x17, 0xda,
	0xe1, 0x25, 0x97, 0x53, 0x6a, 0xd8, 0xcf, 0x0e, 0xbf, 0xcc, 0xae, 0xa2, 0x15, 0xde, 0x01, 0x93,
	0x0b, 0x1e, 0x36, 0xbc, 0xe3, 0x86, 0xfc, 0x35, 0xa3, 0x44, 0x1b, 0x4d, 0x79, 0xe0, 0x4c, 0x3c,
	0x46, 0x8d, 0xf1, 0x3b, 0xb8, 0x3b, 0xaf, 0xdf, 0x1e, 0xa8, 0xed, 0xfb, 0x34, 0x56, 0x78, 0x09,
	0xdd, 0x6b, 0xbd, 0xef, 0x45, 0x95, 0x26, 0xf8, 0xe8, 0xc6, 0x76, 0xfe, 0x3a, 0xe7, 0xc3, 0xc7,
	0xff, 0x51, 0x9b, 0x2b, 0x4d, 0x3a, 0x9f, 0x08, 0xf9, 0x4c, 0xc8, 0xaf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xb8, 0x3e, 0xbe, 0x4e, 0x85, 0x02, 0x00, 0x00,
}
